# Generated by Django 3.1.1 on 2020-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag1',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='tag2',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='tag3',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], default='a', max_length=1),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
