# Generated by Django 3.1.1 on 2020-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201002_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag1',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], default='a', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag2',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], default='a', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag3',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], default='a', max_length=1, null=True),
        ),
    ]
