# Generated by Django 3.1.1 on 2020-10-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201002_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag1',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag3',
        ),
    ]
