# Generated by Django 3.1.1 on 2020-10-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20201003_0217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Vote',
        ),
    ]
